on:
  release:
    types: [published]
name: Publish Python ğŸ distributions ğŸ“¦ to PyPI
jobs:
  build-n-publish:
  - name: Deploy package
    uses: remorses/pypi@master
    with:
      setupfile: ./kenobi/setup.py
      username: ${{ secrets.PYPI_USERNAME }}
      password: ${{Â secrets.PYPI_PASSWORD }}

